name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]  # change this if your branch isn't named "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Clone Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/Basu03/mock_interviewer space-repo

      - name: Sync code to Space and push
        run: |
          cp -r * space-repo/
          cd space-repo
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "🚀 Auto-deploy from GitHub" || echo "No changes to commit"
          git push https://Basu03:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Basu03/mock_interviewer HEAD:main
