import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/subhanjanbasu/Desktop/excel_interviewer/AI-Powered-Excel-Mock-Interviewer/service.json"

from dotenv import load_dotenv
import streamlit as st
from src.graph import build_graph


load_dotenv()


if not os.getenv("GOOGLE_API_KEY"):
    st.error("Error: GOOGLE_API_KEY not found. Please set it in your .env file and restart.")
    st.stop()

app = build_graph()

st.title("🤖 AI-Powered Excel Mock Interviewer")
st.markdown("Welcome! This tool will conduct a mock technical interview to assess your Excel skills. Click 'Start New Interview' to begin.")

# --- Core Functions ---

def run_graph(current_state: dict) -> dict:
    """Invokes the graph and returns the final state of that run."""
    return app.invoke(current_state)

# --- Session State and UI ---

# Initialize session state if it doesn't exist
if "interviewer_state" not in st.session_state:
    st.session_state.interviewer_state = {
        "interview_status": 0, # 0: Not Started, 1: In Progress, 2: Finished
        "interview_history": [],
        "questions": [],
        "question_index": 0,
        "evaluations": [],
        "final_feedback": "",
        "warnings": [] # Initialize the warnings list
    }

# Display the chat history
for message in st.session_state.interviewer_state.get("interview_history", []):
    role, text = message
    if role == "ai":
        with st.chat_message("assistant"):
            st.markdown(text)
    elif role == "human":
        with st.chat_message("user"):
            st.markdown(text)


# Check for and display any warnings generated by the last turn
if "warnings" in st.session_state.interviewer_state and st.session_state.interviewer_state["warnings"]:
    for warning in st.session_state.interviewer_state["warnings"]:
        st.warning(warning)
    # Important: Clear warnings after displaying them so they don't show up again
    st.session_state.interviewer_state["warnings"] = []

# --- Buttons and Input Handling ---

# Button to start a new interview
if st.button("Start New Interview"):
    st.session_state.interviewer_state = {
        "interview_status": 0,
        "interview_history": [],
        "questions": [],
        "question_index": 0,
        "evaluations": [],
        "final_feedback": "",
        "warnings": [] # Also reset warnings on new interview
    }
    # Run the graph to get the welcome message
    initial_state = st.session_state.interviewer_state
    new_state = run_graph(initial_state)
    st.session_state.interviewer_state = new_state
    st.rerun() # Rerun the script to display the new messages

# Handle user input only if the interview is in progress
if st.session_state.interviewer_state["interview_status"] == 1:
    if prompt := st.chat_input("Your answer..."):
        # Add user message to state
        current_state = st.session_state.interviewer_state
        current_state["interview_history"].append(("human", prompt))
        
        # Run the graph to get the AI's response (evaluation + next question/report)
        new_state = run_graph(current_state)
        st.session_state.interviewer_state = new_state
        st.rerun() # Rerun the script to display the new messages

elif st.session_state.interviewer_state["interview_status"] == 2:
    st.success("Interview complete! You can find your performance report above. Click 'Start New Interview' to try again.")